version: '3'

env:
  ROOT_PROJECT: ./fake-store-etl
  DOCKER: docker-compose.yaml

tasks:
  pre_project:
    cmds:
      - echo "CREATE THE AIRLFOW AND THE STORAGE DIRS"
      - echo -e "AIRFLOW_UID=$(id -u)" > $ROOT_PROJECT/.env
      - |
        cat <<EOF >> $ROOT_PROJECT/.env
        CR_HOST=
        CR_USER=
        CR_PASSWORD=
        CR_PORT=
        CR_DBNAME=
        EMAIL=
        EMAIL_PASSWORD=
        SMTP_HOST=
        SMTP_STARTTLS=
        SMTP_SSL=
        SMTP_USER=
        SMTP_PASSWORD=
        SMTP_PORT=
        SMTP_MAIL_FROM=
        EOF
      - mkdir -p $ROOT_PROJECT/{raw_data,processed_data,dags,logs,plugins,config}
      - tree -L 2 $ROOT_PROJECT

  start_project:
      - docker compose -f $ROOT_PROJECT/$DOCKER up airflow-init --build
      - docker compose -f $ROOT_PROJECT/$DOCKER up -d --build
      - docker container ls -a

  down_project:
      - docker compose -f $ROOT_PROJECT/$DOCKER down

  cleanup: 
    cmds:
      - rm -rf  $ROOT_PROJECT/{raw_data,processed_data,logs,plugins,config}
      - rm -f   $ROOT_PROJECT/.env
      - rm -rf  $ROOT_PROJECT/dags/*pycache*
      - rm -rf  $ROOT_PROJECT/dags/*/*pycache*